### PR TITLE
Mouse click

### LINKED ISSUE #57: Mouse support? Is it technically possible?
## Feature Request

A question: Mouse support? Is it technically possible?

### PR DESCRIPTION
**Pull request by theonlytruealex**
# Added the ability to move pieces using the mouse

## Description

I have added the function move_selected_piece_cursor_mouse which replicates the functionality  of move_selected_piece_cursor while instead of the keyboard, it gets its input from the mouse. It is being called by the new handler handle_mouse_events. 

To achieve this i get the coordinates of the mouse and map them onto the board using 4 new variables: top_x, top_y, width and height. They have been added to the board structure and get updates on render. Using this i always know the position of the board and how big the chess squares are. 

When a promotion is happening, these values are instead updated so that they point to the promotion pop-up, specifically to the selectable part (where for example the queen is).

These changes necessitate the passing of a mutable reference to the app variable in order for the top_x, top_y, width and height variables to be updated.

Fixes #57

## How Has This Been Tested?

I have used cargo test, and also tried to move every piece from many configurations, tried to promote and generally played the game a lot.

### CODE REVIEW

**Comment by thomas-mauran** [comment]
This is a great feature, it seems to work fine with the promotion too which is great. Here is few little improvement you can make before we merge I think: 

- Remove the blue square when it was clicked with the mouse
Capture d’écran, le 2024-11-11 à 19 07 03

since this is used to select the case we want to move the piece too. We don't need it when the piece was selected with the mouse.

- we also need to remove the potential cells a piece can go too if it's not his turn
- sometimes after selecting a cell we want to move to the game lags a bit, seems like there is a delay, I don't know what could cause that but we might want to optimize this

Overall it's a very enjoyable feature thanks again for contributing

**Comment by thomas-mauran** [comment]
Hey @theonlytruealex pinging you to know if you will finish this issue or if I shall finish it ?

**Comment by theonlytruealex** [comment]
Hello! I will try to finish it this weekend.

**Comment by theonlytruealex** [comment]
@thomas-mauran sorry for the long wating time, the feature should work fine now!

**Comment by thomas-mauran** [comment]
> @thomas-mauran sorry for the long wating time, the feature should work fine now!

Hey @theonlytruealex no worries, thanks for the PR it's a great feature and working fine. I just found a little bug, when you select a piece and click on the right part of the board (out of it) the games crashes. It might be related to just checking if the coord is part of the board or something like that.

We still have some kind of lag after moving a piece sometimes, this is a minor inconvenience, if you have an idea on how to fix it. Else I will merge with that and find a solution later !

**Comment by theonlytruealex** [comment]
> > @thomas-mauran sorry for the long wating time, the feature should work fine now!
> 
> Hey @theonlytruealex no worries, thanks for the PR it's a great feature and working fine. I just found a little bug, when you select a piece and click on the right part of the board (out of it) the games crashes. It might be related to just checking if the coord is part of the board or something like that.
> 
> We still have some kind of lag after moving a piece sometimes, this is a minor inconvenience, if you have an idea on how to fix it. Else I will merge with that and find a solution later !

Hello again @thomas-mauran
I have not managed to reproduce the bug, could you be more specific as to where exactly on the right you need to click? Sorry for the inconvenience!
About the lag, I'm not sure what is happening or what would cause it.

**Comment by thomas-mauran** [comment]
> Hello again @thomas-mauran I have not managed to reproduce the bug, could you be more specific as to where exactly on the right you need to click? Sorry for the inconvenience! About the lag, I'm not sure what is happening or what would cause it.

Capture d’écran, le 2024-11-23 à 15 48 08

When selecting a piece if you click in the red zone, my bad I said right it's actually left and top part of the board

**Comment by theonlytruealex** [comment]
> > Hello again @thomas-mauran I have not managed to reproduce the bug, could you be more specific as to where exactly on the right you need to click? Sorry for the inconvenience! About the lag, I'm not sure what is happening or what would cause it.
> 
> Capture d’écran, le 2024-11-23 à 15 48 08
> When selecting a piece if you click in the red zone, my bad I said right it's actually left and top part of the board

Thanks for the info! It didn't happen on my device, I think it may be system dependent regarding how each computer treats subtracting a bigger u16 from a smaller one. I added a check so that situation doesn't occur!

**Comment by thomas-mauran** [comment]
Perfect the patch is working fine, I spotted another simple bug related to dividing by 0 on the play against a bot page, here I try to select using a mouse click the game crashes

Capture d’écran, le 2024-11-23 à 16 18 56

**Comment by theonlytruealex** [comment]
> Perfect the patch is working fine, I spotted another simple bug related to dividing by 0 on the play against a bot page, here I try to select using a mouse click the game crashes
> 
> Capture d’écran, le 2024-11-23 à 16 18 56

Fair, I didn't take into account popups on the game page but now utilising the mouse should not be possible when a popup is open.

**Comment by thomas-mauran** [comment]
> Fair, I didn't take into account popups on the game page but now utilising the mouse should not be possible when a popup is open.

Perfect, thanks for your contributions 🎉

**Pull request merged**
