### PR TITLE
Add NetBSD

### PR DESCRIPTION
**Pull request by 0323pin**
# Add NetBSD install instructions

## Description

Add NetBSD install instructions and help me maintaining the package by hosting `Cargo.lock` in the repository.
I've just packaged `chess-tui` for NetBSD and have merged the package into the main branch.

## How Has This Been Tested?

See screenshot.
Commit Log for your reference, http://mail-index.netbsd.org/pkgsrc-changes/2023/12/06/msg288179.html

Thanks!

2023-12-06-105651_1366x768_scrot

### CODE REVIEW

**Comment by 0323pin** [comment]
Packages are released 4 times a year, except for security updates. Next and last release will be by the end of December.

This, of course doesn't apply to those running current, _I.e._ development branch of the packages and OS.

The package will be available to regular users by the end of this month.

**Comment by thomas-mauran** [comment]
> Packages are released 4 times a year, except for security updates. Next, and last release will be by the end of December.
> 
> This, of course doesn't apply to those running current, _I.e._ development branch of the packages and OS.
> 
> The package will be available to regular users by the end of this month.

Thanks for the explanation sounds great

**Comment by 0323pin** [comment]
Thank you! In particular hosting `Cargo.lock` helps a lot. We have a script that collects all the crate dependencies from the file. When, it's not there, I need to do this manually. So, appreciated.

**Comment by thomas-mauran** [comment]
> Thank you! In particular hosting `Cargo.lock` helps a lot. We have a script that collects all the crate dependencies from the file. When, it's not there, I need to do this manually. So, appreciated.

No problem at all, thanks to you for contributing and your knowledge sharing!

**Pull request merged**
