### PR TITLE
Bug fix: Bot move freezes player move

### LINKED ISSUE #83: Bot move freezes player move.
## Description
This bug occurs in a game agains a bot. After the player confirms its move the piece is not drawn on the board and the game waits for the bot's move. Only after the bot's move is received both the player and the bots moves are displayed simultaneously as opposed to being drawn in turn.

This can be observed for bots that take some time to compute the next move.

## To Reproduce
Set up a game against a bot. Make sure that the bot is not extremely optimised (as is [Stockfish](https://stockfishchess.org), for example). Make a move (as a player).

## Expected behaviour

The game will freeze until the bot move is computed. Until that the player move won't be displayed.

## Environment

- OS: MacOS
- Terminal Emulator: Terminal
- Font: ASCII
- Crate version: 1.2.1
- Backend: termion

### PR DESCRIPTION
**Pull request by LucaSain**
# Fix for player move freeze by bot move computation

## Description
On each game tick, the bot move state will be checked and the player move will be rendered first.

This solution relies on a variable exposed through the board enum and an if clause in the app loop. This solution is not perfect and maybe a thread-event approach would be better. Any feedback would be extremely helpful.

Fixes #83

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by thomas-mauran** [comment]
Hello @LucaSain thanks for the contribution the code seems good and logical, do you have any steps to reproduce the bug ? I wasn't able to reproduce it on my computer

**Comment by LucaSain** [comment]
Hi, sorry for late reply.

> Hello @LucaSain thanks for the contribution the code seems good and logical, do you have any steps to reproduce the bug ? I wasn't able to reproduce it on my computer

Try with this bot. It's slower and the issue should visible:
https://github.com/LucaSain/chess-daniel

**Comment by thomas-mauran** [comment]
> Hi, sorry for late reply.
> 
> > Hello @LucaSain thanks for the contribution the code seems good and logical, do you have any steps to reproduce the bug ? I wasn't able to reproduce it on my computer
> 
> Try with this bot. It's slower and the issue should visible: https://github.com/LucaSain/chess-daniel

Ah yes I do see it now, I tried to play a game and lost but the game didn't end after reading the code maybe this is an edge case, I was able to get the Black Won text after selecting the black queen in this position: 
Capture d’écran, le 2024-11-13 à 18 42 14

**Comment by thomas-mauran** [comment]
Hi @LucaSain wanting to know if you will finish this issue or if I shall do it ?

**Comment by LucaSain** [comment]
> Hi @LucaSain wanting to know if you will finish this issue or if I shall do it ?

Working on it right now. I'll try to finish it by tomorrow.

**Comment by thomas-mauran** [comment]
> This should do, however this still feels like a workaround. Should I create a new method or move the checkmate and draft check from the if clause to the switch_turn method?

This will do the trick for now, I am working on a refactor so this will probably be part of it. Thanks for your contribution ! 🎉

**Pull request merged**
