### PR TITLE
fix: various, mostly from `cargo clippy -- --warn clippy::pedantic`

### PR DESCRIPTION
**Pull request by JeromeSchmied**
# Code improvement

## Description

Various code improvements, to make the code more readable, efficient and more `Rust`y

- many functions from `utils.rs` were `self impl`s -> removed them
- in some cases, no `mut` was needed, instead of `for ...` `....iter().collect()` was enough 
- applied numerous `cargo clippy -- --warn clippy::pedantic` fixes, eg.
    - unnecessary_not_if
    - let ... else
    - in some cases take `Coord` as value instead of reference, as it's more efficient
    - add  `;` to line-end if not returning
    - `format!("{}", x)` can be `format!("{x}")`
    - identical `match` branches
    - `String::new()` instead of `"".to_string()`
    - some `fn`-s take `&str` instead of `String`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings, actually the opposite!
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by thomas-mauran — COMMENTED** [review]
Nice fixes, we are having an overflow when eating a another piece thought we need to fix that

**Comment by JeromeSchmied** [comment]
> Nice fixes, we are having an overflow when eating a another piece thought we need to fix that

I'm sorry, didn't quite understand that.

**Comment by thomas-mauran** [comment]
> > Nice fixes, we are having an overflow when eating a another piece thought we need to fix that
> 
> I'm sorry, didn't quite understand that.

To reproduce the bug I found while running on your branch run a classic game, move a white pawn twice, same for black, then eat the black pawn with the white one and the game should quit with a rust panick

**Comment by JeromeSchmied** [comment]
Actually it's interesting, because as far as I'm concerned, no code logic was changed before, so it shouldn't have happened, but luckily enough it seems to be fixed now, by [commit a0a829b](https://github.com/thomas-mauran/chess-tui/pull/77/commits/a0a829b55f27056cd25f06297645a12bf7e79713).

**Comment by thomas-mauran** [comment]
> Actually it's interesting, because as far as I'm concerned, no code logic was changed before, so it shouldn't have happened, but luckily enough it seems to be fixed now, by [commit a0a829b](https://github.com/thomas-mauran/chess-tui/pull/77/commits/a0a829b55f27056cd25f06297645a12bf7e79713).

This is very weird yes, I'm gonna check in detail this commit tonight thank you for fixing it !

**Comment by thomas-mauran** [comment]
Perfect thanks again for yet another contribution @JeromeSchmied

**Pull request merged**
