### PR TITLE
fix: history entry must have a `PieceType`, and therefore does not need to be an `Option<PieceType>`, but rather a `PieceType`

### PR DESCRIPTION
**Pull request by JeromeSchmied**
This PR adds refactor the History to create a new type `pub type HistRec = (PieceType, String);`

### CODE REVIEW

**Comment by thomas-mauran** [comment]
LGTM, you can rebase from main to resolve the conflicts in your IDE and then push again

**Comment by thomas-mauran** [comment]
ping @JeromeSchmied just need to fix the conflict for a merge when you have time

**Comment by JeromeSchmied** [comment]
> ping @JeromeSchmied just need to fix the conflict for a merge when you have time

yup, I know, but I find this rebasing quite tricky, so it'll take some more time

**Comment by thomas-mauran** [comment]
sure thing no problem @JeromeSchmied @ me when you are done mate !

**Comment by thomas-mauran** [comment]
Hello @JeromeSchmied checkout pr #65 @nicholasmello did another refactor of the move history and added a proper struct for it

**Pull request closed without merging**
