### PR TITLE
Fix material difference

### LINKED ISSUE #53: Material difference
## Problem

Material difference is not shown.

## Solution

Display material difference in History.

## Additional context

I guess Lichess has support for this too.

### PR DESCRIPTION
**Pull request by infernosalex**
# Fix material difference

## Description

Fixes #53 and I add a feature to go back to the back menu when you press key 'b'.
 
## How Has This Been Tested?

I don't know how to test this UI feature, perhaps you could help me with some ideas.

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

Screenshot from 2024-11-10 15-51-16

### CODE REVIEW

**Comment by Inf3n0s** [comment]
Ohhh, ok I will check on other computer to check if works or not.
And I will go a pull request after fixing (if something to fix). Anyway on my setup CTRL+'+' doesn't work change the size only of the game board not actually the history block.

**Comment by thomas-mauran** [comment]
> Hi, I just tested and for me works perfectly. What game mode did u tried? ( now I saw if you have font bigger the piece disappears, it's what I asked, can you try with CTRL+'-')

Yes this is it, by zooming out I don't have the problem any more, maybe this can be fixed like we do for the other text on the app

**Comment by Inf3n0s** [comment]
> > Hi, I just tested and for me works perfectly. What game mode did u tried? ( now I saw if you have font bigger the piece disappears, it's what I asked, can you try with CTRL+'-')
> 
> Yes this is it, by zooming out I don't have the problem any more, maybe this can be fixed like we do for the other text on the app

Ok,I didn't find how to fix the text, like you in app, can you provide more context about it, please?

**Comment by thomas-mauran** [comment]
> > > Hi, I just tested and for me works perfectly. What game mode did u tried? ( now I saw if you have font bigger the piece disappears, it's what I asked, can you try with CTRL+'-')
> > 
> > 
> > Yes this is it, by zooming out I don't have the problem any more, maybe this can be fixed like we do for the other text on the app
> 
> Ok,I didn't find how to fix the text, like you in app, can you provide more context about it, please? Or I can just copy the ASCII from to_string function for each piece, instead using symbols?

Hello @Inf3n0s managed to get it working by setting the text to bold, for some reason this makes it stay when zooming, don't ask me why lmao.

**Comment by Inf3n0s** [comment]
> > > > Hi, I just tested and for me works perfectly. What game mode did u tried? ( now I saw if you have font bigger the piece disappears, it's what I asked, can you try with CTRL+'-')
> > > 
> > > 
> > > Yes this is it, by zooming out I don't have the problem any more, maybe this can be fixed like we do for the other text on the app
> > 
> > 
> > Ok,I didn't find how to fix the text, like you in app, can you provide more context about it, please? Or I can just copy the ASCII from to_string function for each piece, instead using symbols?
> 
> Hello @Inf3n0s managed to get it working by setting the text to bold, for some reason this makes it stay when zooming, don't ask me why lmao.

Awesome, so we can merge to main ?

**Comment by thomas-mauran** [comment]
Yep make sure you lint the code as said in the CI: `cargo fmt --check` is not happy but then I can merge

**Comment by Inf3n0s** [comment]
> Yep make sure you lint the code as said in the CI: `cargo fmt --check` is not happy but then I can merge @Inf3n0s

It's fixed now ig.
Thanks you! I will come with update to implement PGN import / export probably soon...

**Pull request merged**
